/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ApiError from './ApiError';
import CancellationCost from './CancellationCost';
import ErrorDetail from './ErrorDetail';





/**
* The CancellationCostError model module.
* @module model/CancellationCostError
* @version 1.0.0
*/
export default class CancellationCostError {
    /**
    * Constructs a new <code>CancellationCostError</code>.
    * @alias module:model/CancellationCostError
    * @class
    * @implements module:model/CancellationCost
    * @implements module:model/ApiError
    * @param amount {Number} Total price of the ride
    * @param currency {String} The ISO 4217 currency code for the amount (e.g. USD)
    * @param description {String} The description for the cost
    */

    constructor(amount, currency, description) {
        

        
        CancellationCost.call(this, amount, currency, description);ApiError.call(this);

        

        
    }

    /**
    * Constructs a <code>CancellationCostError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CancellationCostError} obj Optional instance to populate.
    * @return {module:model/CancellationCostError} The populated <code>CancellationCostError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancellationCostError();

            
            
            CancellationCost.constructFromObject(data, obj);ApiError.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement CancellationCost interface:
    /**
    * Total price of the ride
    * @member {Number} amount
    */
    amount = undefined;
/**
    * The ISO 4217 currency code for the amount (e.g. USD)
    * @member {String} currency
    */
    currency = undefined;
/**
    * The description for the cost
    * @member {String} description
    */
    description = undefined;
/**
    * Token used to confirm the fee when cancelling a request
    * @member {String} token
    */
    token = undefined;
/**
    * How long, in seconds, before the token expires
    * @member {Number} token_duration
    */
    token_duration = undefined;

    // Implement ApiError interface:
    /**
    * A \"slug\" that serves as the error code (eg. \"bad_parameter\")
    * @member {String} error
    */
    error = undefined;
/**
    * @member {Array.<module:model/ErrorDetail>} error_detail
    */
    error_detail = undefined;
/**
    * A user-friendly description of the error (appropriate to show to an end-user)
    * @member {String} error_description
    */
    error_description = undefined;







}


