/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CancellationRequest model module.
* @module model/CancellationRequest
* @version 1.0.0
*/
export default class CancellationRequest {
    /**
    * Constructs a new <code>CancellationRequest</code>.
    * @alias module:model/CancellationRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CancellationRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CancellationRequest} obj Optional instance to populate.
    * @return {module:model/CancellationRequest} The populated <code>CancellationRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancellationRequest();

            
            
            

            if (data.hasOwnProperty('cancel_confirmation_token')) {
                obj['cancel_confirmation_token'] = ApiClient.convertToType(data['cancel_confirmation_token'], 'String');
            }
        }
        return obj;
    }

    /**
    * Token affirming the user accepts the cancellation fee. Required if a cancellation fee is in effect.
    * @member {String} cancel_confirmation_token
    */
    cancel_confirmation_token = undefined;








}


