/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Charge model module.
* @module model/Charge
* @version 1.0.0
*/
export default class Charge {
    /**
    * Constructs a new <code>Charge</code>.
    * @alias module:model/Charge
    * @class
    * @param amount {Number} The line item amount
    * @param currency {String} The currency for the amount
    * @param paymentMethod {String} The payment method display name.
    */

    constructor(amount, currency, paymentMethod) {
        

        
        

        this['amount'] = amount;this['currency'] = currency;this['payment_method'] = paymentMethod;

        
    }

    /**
    * Constructs a <code>Charge</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Charge} obj Optional instance to populate.
    * @return {module:model/Charge} The populated <code>Charge</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Charge();

            
            
            

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('payment_method')) {
                obj['payment_method'] = ApiClient.convertToType(data['payment_method'], 'String');
            }
        }
        return obj;
    }

    /**
    * The line item amount
    * @member {Number} amount
    */
    amount = undefined;
    /**
    * The currency for the amount
    * @member {String} currency
    */
    currency = undefined;
    /**
    * The payment method display name.
    * @member {String} payment_method
    */
    payment_method = undefined;








}


