/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CostEstimate from './CostEstimate';





/**
* The CostEstimateResponse model module.
* @module model/CostEstimateResponse
* @version 1.0.0
*/
export default class CostEstimateResponse {
    /**
    * Constructs a new <code>CostEstimateResponse</code>.
    * @alias module:model/CostEstimateResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CostEstimateResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CostEstimateResponse} obj Optional instance to populate.
    * @return {module:model/CostEstimateResponse} The populated <code>CostEstimateResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CostEstimateResponse();

            
            
            

            if (data.hasOwnProperty('cost_estimates')) {
                obj['cost_estimates'] = ApiClient.convertToType(data['cost_estimates'], [CostEstimate]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/CostEstimate>} cost_estimates
    */
    cost_estimates = undefined;








}


