/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Cost model module.
* @module model/Cost
* @version 1.0.0
*/
export default class Cost {
    /**
    * Constructs a new <code>Cost</code>.
    * @alias module:model/Cost
    * @class
    * @param amount {Number} Total price of the ride
    * @param currency {String} The ISO 4217 currency code for the amount (e.g. USD)
    * @param description {String} The description for the cost
    */

    constructor(amount, currency, description) {
        

        
        

        this['amount'] = amount;this['currency'] = currency;this['description'] = description;

        
    }

    /**
    * Constructs a <code>Cost</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Cost} obj Optional instance to populate.
    * @return {module:model/Cost} The populated <code>Cost</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cost();

            
            
            

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * Total price of the ride
    * @member {Number} amount
    */
    amount = undefined;
    /**
    * The ISO 4217 currency code for the amount (e.g. USD)
    * @member {String} currency
    */
    currency = undefined;
    /**
    * The description for the cost
    * @member {String} description
    */
    description = undefined;








}


