/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import LatLng from './LatLng';





/**
* The CurrentRideLocation model module.
* @module model/CurrentRideLocation
* @version 1.0.0
*/
export default class CurrentRideLocation {
    /**
    * Constructs a new <code>CurrentRideLocation</code>.
    * @alias module:model/CurrentRideLocation
    * @class
    * @implements module:model/LatLng
    * @param lat {Number} The latitude component of a location
    * @param lng {Number} The longitude component of a location
    */

    constructor(lat, lng) {
        

        
        LatLng.call(this, lat, lng);

        

        
    }

    /**
    * Constructs a <code>CurrentRideLocation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CurrentRideLocation} obj Optional instance to populate.
    * @return {module:model/CurrentRideLocation} The populated <code>CurrentRideLocation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CurrentRideLocation();

            
            
            LatLng.constructFromObject(data, obj);

            if (data.hasOwnProperty('bearing')) {
                obj['bearing'] = ApiClient.convertToType(data['bearing'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Bearing of the driver's car in degrees
    * @member {Number} bearing
    */
    bearing = undefined;


    // Implement LatLng interface:
    /**
    * The latitude component of a location
    * @member {Number} lat
    */
    lat = undefined;
/**
    * The longitude component of a location
    * @member {Number} lng
    */
    lng = undefined;







}


