/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ErrorDetail model module.
* @module model/ErrorDetail
* @version 1.0.0
*/
export default class ErrorDetail {
    /**
    * Constructs a new <code>ErrorDetail</code>.
    * An object with a single key-value pair, where the key is the name of the invalid parameter, and the value is a description of the error. 
    * @alias module:model/ErrorDetail
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ErrorDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorDetail} obj Optional instance to populate.
    * @return {module:model/ErrorDetail} The populated <code>ErrorDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorDetail();

            
            
            

            if (data.hasOwnProperty('field_name')) {
                obj['field_name'] = ApiClient.convertToType(data['field_name'], 'String');
            }
        }
        return obj;
    }

    /**
    * description of the error
    * @member {String} field_name
    */
    field_name = undefined;








}


