/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Eta from './Eta';





/**
* The EtaEstimateResponse model module.
* @module model/EtaEstimateResponse
* @version 1.0.0
*/
export default class EtaEstimateResponse {
    /**
    * Constructs a new <code>EtaEstimateResponse</code>.
    * @alias module:model/EtaEstimateResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EtaEstimateResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EtaEstimateResponse} obj Optional instance to populate.
    * @return {module:model/EtaEstimateResponse} The populated <code>EtaEstimateResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EtaEstimateResponse();

            
            
            

            if (data.hasOwnProperty('eta_estimates')) {
                obj['eta_estimates'] = ApiClient.convertToType(data['eta_estimates'], [Eta]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Eta>} eta_estimates
    */
    eta_estimates = undefined;








}


