/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The LineItem model module.
* @module model/LineItem
* @version 1.0.0
*/
export default class LineItem {
    /**
    * Constructs a new <code>LineItem</code>.
    * @alias module:model/LineItem
    * @class
    * @param type {String} The line item display name for a charge item
    * @param amount {Number} The line item amount
    * @param currency {String} The currency for the amount
    */

    constructor(type, amount, currency) {
        

        
        

        this['type'] = type;this['amount'] = amount;this['currency'] = currency;

        
    }

    /**
    * Constructs a <code>LineItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LineItem} obj Optional instance to populate.
    * @return {module:model/LineItem} The populated <code>LineItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LineItem();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
    * The line item display name for a charge item
    * @member {String} type
    */
    type = undefined;
    /**
    * The line item amount
    * @member {Number} amount
    */
    amount = undefined;
    /**
    * The currency for the amount
    * @member {String} currency
    */
    currency = undefined;








}


