/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NearbyDriversByRideType from './NearbyDriversByRideType';





/**
* The NearbyDriversResponse model module.
* @module model/NearbyDriversResponse
* @version 1.0.0
*/
export default class NearbyDriversResponse {
    /**
    * Constructs a new <code>NearbyDriversResponse</code>.
    * @alias module:model/NearbyDriversResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>NearbyDriversResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NearbyDriversResponse} obj Optional instance to populate.
    * @return {module:model/NearbyDriversResponse} The populated <code>NearbyDriversResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NearbyDriversResponse();

            
            
            

            if (data.hasOwnProperty('nearby_drivers')) {
                obj['nearby_drivers'] = ApiClient.convertToType(data['nearby_drivers'], [NearbyDriversByRideType]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/NearbyDriversByRideType>} nearby_drivers
    */
    nearby_drivers = undefined;








}


