/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import LatLng from './LatLng';





/**
* The NearbyDriver model module.
* @module model/NearbyDriver
* @version 1.0.0
*/
export default class NearbyDriver {
    /**
    * Constructs a new <code>NearbyDriver</code>.
    * @alias module:model/NearbyDriver
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>NearbyDriver</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NearbyDriver} obj Optional instance to populate.
    * @return {module:model/NearbyDriver} The populated <code>NearbyDriver</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NearbyDriver();

            
            
            

            if (data.hasOwnProperty('locations')) {
                obj['locations'] = ApiClient.convertToType(data['locations'], [LatLng]);
            }
        }
        return obj;
    }

    /**
    * the lastest recorded driver locations up to 5 sorted in chronological order.
    * @member {Array.<module:model/LatLng>} locations
    */
    locations = undefined;








}


