/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NearbyDriver from './NearbyDriver';





/**
* The NearbyDriversByRideType model module.
* @module model/NearbyDriversByRideType
* @version 1.0.0
*/
export default class NearbyDriversByRideType {
    /**
    * Constructs a new <code>NearbyDriversByRideType</code>.
    * @alias module:model/NearbyDriversByRideType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>NearbyDriversByRideType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NearbyDriversByRideType} obj Optional instance to populate.
    * @return {module:model/NearbyDriversByRideType} The populated <code>NearbyDriversByRideType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NearbyDriversByRideType();

            
            
            

            if (data.hasOwnProperty('ride_type')) {
                obj['ride_type'] = ApiClient.convertToType(data['ride_type'], 'String');
            }
            if (data.hasOwnProperty('drivers')) {
                obj['drivers'] = ApiClient.convertToType(data['drivers'], [NearbyDriver]);
            }
        }
        return obj;
    }

    /**
    * driver's ride type. if driver is eligable for several ride types, he will be duplicated.
    * @member {String} ride_type
    */
    ride_type = undefined;
    /**
    * list of nearby drivers group by ride type sorted by eta
    * @member {Array.<module:model/NearbyDriver>} drivers
    */
    drivers = undefined;








}


