/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UserDetail from './UserDetail';





/**
* The PassengerDetail model module.
* @module model/PassengerDetail
* @version 1.0.0
*/
export default class PassengerDetail {
    /**
    * Constructs a new <code>PassengerDetail</code>.
    * @alias module:model/PassengerDetail
    * @class
    * @implements module:model/UserDetail
    * @param firstName {String} The passenger's first name
    * @param imageUrl {String} The passenger's profile image
    * @param rating {String} The passenger's rating
    */

    constructor(firstName, imageUrl, rating) {
        

        
        UserDetail.call(this, firstName, imageUrl, rating);

        

        
    }

    /**
    * Constructs a <code>PassengerDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PassengerDetail} obj Optional instance to populate.
    * @return {module:model/PassengerDetail} The populated <code>PassengerDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PassengerDetail();

            
            
            UserDetail.constructFromObject(data, obj);

            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * The passenger's last name
    * @member {String} last_name
    */
    last_name = undefined;
    /**
    * The passenger's lyft user id
    * @member {String} user_id
    */
    user_id = undefined;


    // Implement UserDetail interface:
    /**
    * The passenger's first name
    * @member {String} first_name
    */
    first_name = undefined;
/**
    * The passenger's profile image
    * @member {String} image_url
    */
    image_url = undefined;
/**
    * The passenger's rating
    * @member {String} rating
    */
    rating = undefined;







}


