/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Location from './Location';





/**
* The PickupDropoffLocation model module.
* @module model/PickupDropoffLocation
* @version 1.0.0
*/
export default class PickupDropoffLocation {
    /**
    * Constructs a new <code>PickupDropoffLocation</code>.
    * @alias module:model/PickupDropoffLocation
    * @class
    * @implements module:model/Location
    * @param lat {Number} The latitude component of a location
    * @param lng {Number} The longitude component of a location
    */

    constructor(lat, lng) {
        

        
        Location.call(this, lat, lng);

        

        
    }

    /**
    * Constructs a <code>PickupDropoffLocation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PickupDropoffLocation} obj Optional instance to populate.
    * @return {module:model/PickupDropoffLocation} The populated <code>PickupDropoffLocation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PickupDropoffLocation();

            
            
            Location.constructFromObject(data, obj);

            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
        }
        return obj;
    }

    /**
    * Server time when the location object is created
    * @member {Date} time
    */
    time = undefined;


    // Implement Location interface:
    /**
    * The latitude component of a location
    * @member {Number} lat
    */
    lat = undefined;
/**
    * The longitude component of a location
    * @member {Number} lng
    */
    lng = undefined;
/**
    * A human readable address at/near the given location
    * @member {String} address
    */
    address = undefined;







}


