/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The RatingRequest model module.
* @module model/RatingRequest
* @version 1.0.0
*/
export default class RatingRequest {
    /**
    * Constructs a new <code>RatingRequest</code>.
    * Rating and optional feedback and tip
    * @alias module:model/RatingRequest
    * @class
    * @param rating {Number} The passenger's rating of this ride from 1 to 5
    */

    constructor(rating) {
        

        
        

        this['rating'] = rating;

        
    }

    /**
    * Constructs a <code>RatingRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RatingRequest} obj Optional instance to populate.
    * @return {module:model/RatingRequest} The populated <code>RatingRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RatingRequest();

            
            
            

            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('feedback')) {
                obj['feedback'] = ApiClient.convertToType(data['feedback'], 'String');
            }
            if (data.hasOwnProperty('tip')) {
                obj['tip'] = ApiClient.convertToType(data['tip'], Object);
            }
        }
        return obj;
    }

    /**
    * The passenger's rating of this ride from 1 to 5
    * @member {Number} rating
    */
    rating = undefined;
    /**
    * The passenger's written feedback about this ride
    * @member {String} feedback
    */
    feedback = undefined;
    /**
    * Tip amount in minor units and tip currency
    * @member {Object} tip
    */
    tip = undefined;








}


