/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* Enum class RideTypeEnum.
* @enum {}
* @readonly
*/
export default class RideTypeEnum {
    
        /**
         * value: "lyft"
         * @const
         */
        lyft = "lyft";

    
        /**
         * value: "lyft_line"
         * @const
         */
        lyft_line = "lyft_line";

    
        /**
         * value: "lyft_plus"
         * @const
         */
        lyft_plus = "lyft_plus";

    
        /**
         * value: "lyft_premier"
         * @const
         */
        lyft_premier = "lyft_premier";

    
        /**
         * value: "lyft_lux"
         * @const
         */
        lyft_lux = "lyft_lux";

    
        /**
         * value: "lyft_luxsuv"
         * @const
         */
        lyft_luxsuv = "lyft_luxsuv";

    

    /**
    * Returns a <code>RideTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/RideTypeEnum} The enum <code>RideTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


