/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ErrorDetail from './ErrorDetail';





/**
* The RideRequestError model module.
* @module model/RideRequestError
* @version 1.0.0
*/
export default class RideRequestError {
    /**
    * Constructs a new <code>RideRequestError</code>.
    * Details about why a request failed, such as missing or invalid parameters
    * @alias module:model/RideRequestError
    * @class
    * @param error {String} A \"slug\" that serves as the error code (eg. \"bad_parameter\")
    */

    constructor(error) {
        

        
        

        this['error'] = error;

        
    }

    /**
    * Constructs a <code>RideRequestError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RideRequestError} obj Optional instance to populate.
    * @return {module:model/RideRequestError} The populated <code>RideRequestError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RideRequestError();

            
            
            

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('error_detail')) {
                obj['error_detail'] = ApiClient.convertToType(data['error_detail'], [ErrorDetail]);
            }
            if (data.hasOwnProperty('error_description')) {
                obj['error_description'] = ApiClient.convertToType(data['error_description'], 'String');
            }
            if (data.hasOwnProperty('primetime_percentage')) {
                obj['primetime_percentage'] = ApiClient.convertToType(data['primetime_percentage'], 'String');
            }
            if (data.hasOwnProperty('primetime_multiplier')) {
                obj['primetime_multiplier'] = ApiClient.convertToType(data['primetime_multiplier'], 'Number');
            }
            if (data.hasOwnProperty('primetime_confirmation_token')) {
                obj['primetime_confirmation_token'] = ApiClient.convertToType(data['primetime_confirmation_token'], 'String');
            }
            if (data.hasOwnProperty('cost_token')) {
                obj['cost_token'] = ApiClient.convertToType(data['cost_token'], 'String');
            }
            if (data.hasOwnProperty('token_duration')) {
                obj['token_duration'] = ApiClient.convertToType(data['token_duration'], 'String');
            }
        }
        return obj;
    }

    /**
    * A \"slug\" that serves as the error code (eg. \"bad_parameter\")
    * @member {String} error
    */
    error = undefined;
    /**
    * @member {Array.<module:model/ErrorDetail>} error_detail
    */
    error_detail = undefined;
    /**
    * A user-friendly description of the error (appropriate to show to an end-user)
    * @member {String} error_description
    */
    error_description = undefined;
    /**
    * Current Prime Time percentage
    * @member {String} primetime_percentage
    */
    primetime_percentage = undefined;
    /**
    * Current Prime Time multiplier (eg. if primetime_percentage is 100%, primetime_multiplier will be 2.0)
    * @member {Number} primetime_multiplier
    */
    primetime_multiplier = undefined;
    /**
    * A token that confirms the user has accepted current Prime Time charges (Deprecated)
    * @member {String} primetime_confirmation_token
    */
    primetime_confirmation_token = undefined;
    /**
    * A token that confirms the user has accepted current Prime Time and/or fixed price charges
    * @member {String} cost_token
    */
    cost_token = undefined;
    /**
    * Validity of the token in seconds
    * @member {String} token_duration
    */
    token_duration = undefined;








}


