/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import PassengerDetail from './PassengerDetail';
import RideStatusEnum from './RideStatusEnum';





/**
* The RideRequest model module.
* @module model/RideRequest
* @version 1.0.0
*/
export default class RideRequest {
    /**
    * Constructs a new <code>RideRequest</code>.
    * Minimal set of ride details
    * @alias module:model/RideRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RideRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RideRequest} obj Optional instance to populate.
    * @return {module:model/RideRequest} The populated <code>RideRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RideRequest();

            
            
            

            if (data.hasOwnProperty('ride_id')) {
                obj['ride_id'] = ApiClient.convertToType(data['ride_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = RideStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], Object);
            }
            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], Object);
            }
            if (data.hasOwnProperty('passenger')) {
                obj['passenger'] = PassengerDetail.constructFromObject(data['passenger']);
            }
        }
        return obj;
    }

    /**
    * The ID of the requested ride
    * @member {String} ride_id
    */
    ride_id = undefined;
    /**
    * @member {module:model/RideStatusEnum} status
    */
    status = undefined;
    /**
    * The *requested* location for passenger pickup
    * @member {Object} origin
    */
    origin = undefined;
    /**
    * The *requested* location for passenger drop off
    * @member {Object} destination
    */
    destination = undefined;
    /**
    * @member {module:model/PassengerDetail} passenger
    */
    passenger = undefined;








}


