/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RideType from './RideType';





/**
* The RideTypesResponse model module.
* @module model/RideTypesResponse
* @version 1.0.0
*/
export default class RideTypesResponse {
    /**
    * Constructs a new <code>RideTypesResponse</code>.
    * @alias module:model/RideTypesResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RideTypesResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RideTypesResponse} obj Optional instance to populate.
    * @return {module:model/RideTypesResponse} The populated <code>RideTypesResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RideTypesResponse();

            
            
            

            if (data.hasOwnProperty('ride_types')) {
                obj['ride_types'] = ApiClient.convertToType(data['ride_types'], [RideType]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/RideType>} ride_types
    */
    ride_types = undefined;








}


