/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Charge from './Charge';
import LineItem from './LineItem';





/**
* The RideReceipt model module.
* @module model/RideReceipt
* @version 1.0.0
*/
export default class RideReceipt {
    /**
    * Constructs a new <code>RideReceipt</code>.
    * Receipt information of a processed ride.
    * @alias module:model/RideReceipt
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RideReceipt</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RideReceipt} obj Optional instance to populate.
    * @return {module:model/RideReceipt} The populated <code>RideReceipt</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RideReceipt();

            
            
            

            if (data.hasOwnProperty('ride_id')) {
                obj['ride_id'] = ApiClient.convertToType(data['ride_id'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], Object);
            }
            if (data.hasOwnProperty('line_items')) {
                obj['line_items'] = ApiClient.convertToType(data['line_items'], [LineItem]);
            }
            if (data.hasOwnProperty('charges')) {
                obj['charges'] = ApiClient.convertToType(data['charges'], [Charge]);
            }
            if (data.hasOwnProperty('requested_at')) {
                obj['requested_at'] = ApiClient.convertToType(data['requested_at'], 'Date');
            }
            if (data.hasOwnProperty('ride_profile')) {
                obj['ride_profile'] = ApiClient.convertToType(data['ride_profile'], Object);
            }
        }
        return obj;
    }

    /**
    * The unique ID of this ride
    * @member {String} ride_id
    */
    ride_id = undefined;
    /**
    * The total price for the current ride
    * @member {Object} price
    */
    price = undefined;
    /**
    * The break down of line items
    * @member {Array.<module:model/LineItem>} line_items
    */
    line_items = undefined;
    /**
    * The break down of charge method
    * @member {Array.<module:model/Charge>} charges
    */
    charges = undefined;
    /**
    * The ride requested timestamp in date and time
    * @member {Date} requested_at
    */
    requested_at = undefined;
    /**
    * Indicates whether the ride was requested from the business profile or personal profile of the user. 
    * @member {Object} ride_profile
    */
    ride_profile = undefined;








}


