/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RideTypeEnum from './RideTypeEnum';





/**
* The Ride model module.
* @module model/Ride
* @version 1.0.0
*/
export default class Ride {
    /**
    * Constructs a new <code>Ride</code>.
    * Represents a requested, ongoing, or finished Lyft ride
    * @alias module:model/Ride
    * @class
    * @param rideType {module:model/RideTypeEnum} 
    * @param origin {Object} The *requested* location for passenger pickup
    */

    constructor(rideType, origin) {
        

        
        

        this['ride_type'] = rideType;this['origin'] = origin;

        
    }

    /**
    * Constructs a <code>Ride</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Ride} obj Optional instance to populate.
    * @return {module:model/Ride} The populated <code>Ride</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Ride();

            
            
            

            if (data.hasOwnProperty('ride_type')) {
                obj['ride_type'] = RideTypeEnum.constructFromObject(data['ride_type']);
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], Object);
            }
            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], Object);
            }
            if (data.hasOwnProperty('primetime_confirmation_token')) {
                obj['primetime_confirmation_token'] = ApiClient.convertToType(data['primetime_confirmation_token'], 'String');
            }
            if (data.hasOwnProperty('cost_token')) {
                obj['cost_token'] = ApiClient.convertToType(data['cost_token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/RideTypeEnum} ride_type
    */
    ride_type = undefined;
    /**
    * The *requested* location for passenger pickup
    * @member {Object} origin
    */
    origin = undefined;
    /**
    * The *requested* location for passenger drop off
    * @member {Object} destination
    */
    destination = undefined;
    /**
    * A token that confirms the user has accepted current primetime charges (Deprecated)
    * @member {String} primetime_confirmation_token
    */
    primetime_confirmation_token = undefined;
    /**
    * A token that confirms the user has accepted current Prime Time and/or fixed price charges
    * @member {String} cost_token
    */
    cost_token = undefined;








}


