/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import PricingDetails from './PricingDetails';
import RideTypeEnum from './RideTypeEnum';





/**
* The RideType model module.
* @module model/RideType
* @version 1.0.0
*/
export default class RideType {
    /**
    * Constructs a new <code>RideType</code>.
    * @alias module:model/RideType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RideType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RideType} obj Optional instance to populate.
    * @return {module:model/RideType} The populated <code>RideType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RideType();

            
            
            

            if (data.hasOwnProperty('ride_type')) {
                obj['ride_type'] = RideTypeEnum.constructFromObject(data['ride_type']);
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('seats')) {
                obj['seats'] = ApiClient.convertToType(data['seats'], 'Number');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('pricing_details')) {
                obj['pricing_details'] = PricingDetails.constructFromObject(data['pricing_details']);
            }
            if (data.hasOwnProperty('scheduled_pricing_details')) {
                obj['scheduled_pricing_details'] = PricingDetails.constructFromObject(data['scheduled_pricing_details']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/RideTypeEnum} ride_type
    */
    ride_type = undefined;
    /**
    * A human readable description of the ride type
    * @member {String} display_name
    */
    display_name = undefined;
    /**
    * The maximum number of seats available for rides requested with this ride type
    * @member {Number} seats
    */
    seats = undefined;
    /**
    * The URL of an image representing this ride type
    * @member {String} image_url
    */
    image_url = undefined;
    /**
    * @member {module:model/PricingDetails} pricing_details
    */
    pricing_details = undefined;
    /**
    * @member {module:model/PricingDetails} scheduled_pricing_details
    */
    scheduled_pricing_details = undefined;








}


