/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RideDetail from './RideDetail';





/**
* The RidesResponse model module.
* @module model/RidesResponse
* @version 1.0.0
*/
export default class RidesResponse {
    /**
    * Constructs a new <code>RidesResponse</code>.
    * @alias module:model/RidesResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RidesResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RidesResponse} obj Optional instance to populate.
    * @return {module:model/RidesResponse} The populated <code>RidesResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RidesResponse();

            
            
            

            if (data.hasOwnProperty('ride_history')) {
                obj['ride_history'] = ApiClient.convertToType(data['ride_history'], [RideDetail]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/RideDetail>} ride_history
    */
    ride_history = undefined;








}


