/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* Enum class RideStatusEnum.
* @enum {}
* @readonly
*/
export default class RideStatusEnum {
    
        /**
         * value: "pending"
         * @const
         */
        pending = "pending";

    
        /**
         * value: "accepted"
         * @const
         */
        accepted = "accepted";

    
        /**
         * value: "arrived"
         * @const
         */
        arrived = "arrived";

    
        /**
         * value: "pickedUp"
         * @const
         */
        pickedUp = "pickedUp";

    
        /**
         * value: "droppedOff"
         * @const
         */
        droppedOff = "droppedOff";

    
        /**
         * value: "canceled"
         * @const
         */
        canceled = "canceled";

    
        /**
         * value: "scheduled"
         * @const
         */
        scheduled = "scheduled";

    
        /**
         * value: "unknown"
         * @const
         */
        unknown = "unknown";

    

    /**
    * Returns a <code>RideStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/RideStatusEnum} The enum <code>RideStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


