/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SandboxDriverAvailability model module.
* @module model/SandboxDriverAvailability
* @version 1.0.0
*/
export default class SandboxDriverAvailability {
    /**
    * Constructs a new <code>SandboxDriverAvailability</code>.
    * @alias module:model/SandboxDriverAvailability
    * @class
    * @param lat {Number} The latitude component of a location
    * @param lng {Number} The longitude component of a location
    * @param driverAvailability {Boolean} The availability of driver in a region
    */

    constructor(lat, lng, driverAvailability) {
        

        
        

        this['lat'] = lat;this['lng'] = lng;this['driver_availability'] = driverAvailability;

        
    }

    /**
    * Constructs a <code>SandboxDriverAvailability</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SandboxDriverAvailability} obj Optional instance to populate.
    * @return {module:model/SandboxDriverAvailability} The populated <code>SandboxDriverAvailability</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SandboxDriverAvailability();

            
            
            

            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
            if (data.hasOwnProperty('driver_availability')) {
                obj['driver_availability'] = ApiClient.convertToType(data['driver_availability'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * The latitude component of a location
    * @member {Number} lat
    */
    lat = undefined;
    /**
    * The longitude component of a location
    * @member {Number} lng
    */
    lng = undefined;
    /**
    * The availability of driver in a region
    * @member {Boolean} driver_availability
    */
    driver_availability = undefined;








}


