/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RideStatusEnum from './RideStatusEnum';





/**
* The SandboxRideStatus model module.
* @module model/SandboxRideStatus
* @version 1.0.0
*/
export default class SandboxRideStatus {
    /**
    * Constructs a new <code>SandboxRideStatus</code>.
    * @alias module:model/SandboxRideStatus
    * @class
    * @param status {module:model/RideStatusEnum} 
    */

    constructor(status) {
        

        
        

        this['status'] = status;

        
    }

    /**
    * Constructs a <code>SandboxRideStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SandboxRideStatus} obj Optional instance to populate.
    * @return {module:model/SandboxRideStatus} The populated <code>SandboxRideStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SandboxRideStatus();

            
            
            

            if (data.hasOwnProperty('status')) {
                obj['status'] = RideStatusEnum.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/RideStatusEnum} status
    */
    status = undefined;








}


