/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RideTypeEnum from './RideTypeEnum';





/**
* The SandboxRideType model module.
* @module model/SandboxRideType
* @version 1.0.0
*/
export default class SandboxRideType {
    /**
    * Constructs a new <code>SandboxRideType</code>.
    * @alias module:model/SandboxRideType
    * @class
    * @param lat {Number} The latitude component of a location
    * @param lng {Number} The longitude component of a location
    * @param rideTypes {Array.<module:model/RideTypeEnum>} 
    */

    constructor(lat, lng, rideTypes) {
        

        
        

        this['lat'] = lat;this['lng'] = lng;this['ride_types'] = rideTypes;

        
    }

    /**
    * Constructs a <code>SandboxRideType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SandboxRideType} obj Optional instance to populate.
    * @return {module:model/SandboxRideType} The populated <code>SandboxRideType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SandboxRideType();

            
            
            

            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
            if (data.hasOwnProperty('ride_types')) {
                obj['ride_types'] = ApiClient.convertToType(data['ride_types'], [RideTypeEnum]);
            }
        }
        return obj;
    }

    /**
    * The latitude component of a location
    * @member {Number} lat
    */
    lat = undefined;
    /**
    * The longitude component of a location
    * @member {Number} lng
    */
    lng = undefined;
    /**
    * @member {Array.<module:model/RideTypeEnum>} ride_types
    */
    ride_types = undefined;








}


