/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RideStatusEnum from './RideStatusEnum';





/**
* The SandboxRideUpdate model module.
* @module model/SandboxRideUpdate
* @version 1.0.0
*/
export default class SandboxRideUpdate {
    /**
    * Constructs a new <code>SandboxRideUpdate</code>.
    * Response when a sandbox ride is propagated through ride status
    * @alias module:model/SandboxRideUpdate
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SandboxRideUpdate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SandboxRideUpdate} obj Optional instance to populate.
    * @return {module:model/SandboxRideUpdate} The populated <code>SandboxRideUpdate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SandboxRideUpdate();

            
            
            

            if (data.hasOwnProperty('ride_id')) {
                obj['ride_id'] = ApiClient.convertToType(data['ride_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = RideStatusEnum.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
    * The ID of the ride
    * @member {String} ride_id
    */
    ride_id = undefined;
    /**
    * @member {module:model/RideStatusEnum} status
    */
    status = undefined;








}


