/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Tip model module.
* @module model/Tip
* @version 1.0.0
*/
export default class Tip {
    /**
    * Constructs a new <code>Tip</code>.
    * @alias module:model/Tip
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Tip</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Tip} obj Optional instance to populate.
    * @return {module:model/Tip} The populated <code>Tip</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tip();

            
            
            

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
    * A tip for the driver in cents. To be charged to the user's default charge account.
    * @member {Number} amount
    */
    amount = undefined;
    /**
    * The currency in which you want to tip. e.g. USD
    * @member {String} currency
    */
    currency = undefined;








}


