/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Tip from './Tip';





/**
* The TipParams model module.
* @module model/TipParams
* @version 1.0.0
*/
export default class TipParams {
    /**
    * Constructs a new <code>TipParams</code>.
    * @alias module:model/TipParams
    * @class
    * @implements module:model/Tip
    */

    constructor() {
        

        
        Tip.call(this);

        

        
    }

    /**
    * Constructs a <code>TipParams</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TipParams} obj Optional instance to populate.
    * @return {module:model/TipParams} The populated <code>TipParams</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TipParams();

            
            
            Tip.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement Tip interface:
    /**
    * A tip for the driver in cents. To be charged to the user's default charge account.
    * @member {Number} amount
    */
    amount = undefined;
/**
    * The currency in which you want to tip. e.g. USD
    * @member {String} currency
    */
    currency = undefined;







}


