/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The UserDetail model module.
* @module model/UserDetail
* @version 1.0.0
*/
export default class UserDetail {
    /**
    * Constructs a new <code>UserDetail</code>.
    * @alias module:model/UserDetail
    * @class
    * @param firstName {String} The passenger's first name
    * @param imageUrl {String} The passenger's profile image
    * @param rating {String} The passenger's rating
    */

    constructor(firstName, imageUrl, rating) {
        

        
        

        this['first_name'] = firstName;this['image_url'] = imageUrl;this['rating'] = rating;

        
    }

    /**
    * Constructs a <code>UserDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserDetail} obj Optional instance to populate.
    * @return {module:model/UserDetail} The populated <code>UserDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDetail();

            
            
            

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'String');
            }
        }
        return obj;
    }

    /**
    * The passenger's first name
    * @member {String} first_name
    */
    first_name = undefined;
    /**
    * The passenger's profile image
    * @member {String} image_url
    */
    image_url = undefined;
    /**
    * The passenger's rating
    * @member {String} rating
    */
    rating = undefined;








}


