/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The VehicleDetail model module.
* @module model/VehicleDetail
* @version 1.0.0
*/
export default class VehicleDetail {
    /**
    * Constructs a new <code>VehicleDetail</code>.
    * @alias module:model/VehicleDetail
    * @class
    * @param make {String} The vehicle's maker
    * @param model {String} The vehicle's model
    * @param year {Number} The vehicle's model year
    * @param licensePlate {String} The vehicle's license plate
    * @param licensePlateState {String} The vehicle's license plate state
    * @param color {String} The vehicle's color
    * @param imageUrl {String} The vehicle's image url
    */

    constructor(make, model, year, licensePlate, licensePlateState, color, imageUrl) {
        

        
        

        this['make'] = make;this['model'] = model;this['year'] = year;this['license_plate'] = licensePlate;this['license_plate_state'] = licensePlateState;this['color'] = color;this['image_url'] = imageUrl;

        
    }

    /**
    * Constructs a <code>VehicleDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VehicleDetail} obj Optional instance to populate.
    * @return {module:model/VehicleDetail} The populated <code>VehicleDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleDetail();

            
            
            

            if (data.hasOwnProperty('make')) {
                obj['make'] = ApiClient.convertToType(data['make'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('license_plate')) {
                obj['license_plate'] = ApiClient.convertToType(data['license_plate'], 'String');
            }
            if (data.hasOwnProperty('license_plate_state')) {
                obj['license_plate_state'] = ApiClient.convertToType(data['license_plate_state'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
        }
        return obj;
    }

    /**
    * The vehicle's maker
    * @member {String} make
    */
    make = undefined;
    /**
    * The vehicle's model
    * @member {String} model
    */
    model = undefined;
    /**
    * The vehicle's model year
    * @member {Number} year
    */
    year = undefined;
    /**
    * The vehicle's license plate
    * @member {String} license_plate
    */
    license_plate = undefined;
    /**
    * The vehicle's license plate state
    * @member {String} license_plate_state
    */
    license_plate_state = undefined;
    /**
    * The vehicle's color
    * @member {String} color
    */
    color = undefined;
    /**
    * The vehicle's image url
    * @member {String} image_url
    */
    image_url = undefined;








}


