/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiError from '../model/ApiError';
import CostEstimateResponse from '../model/CostEstimateResponse';
import EtaEstimateResponse from '../model/EtaEstimateResponse';
import NearbyDriversResponse from '../model/NearbyDriversResponse';
import RideTypesResponse from '../model/RideTypesResponse';

/**
* Public service.
* @module api/PublicApi
* @version 1.0.0
*/
export default class PublicApi {

    /**
    * Constructs a new PublicApi. 
    * @alias module:api/PublicApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Cost estimates
     * Estimate the cost of taking a Lyft between two points. 
     * @param {Number} startLat Latitude of the starting location
     * @param {Number} startLng Longitude of the starting location
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.rideType ID of a ride type
     * @param {Number} opts.endLat Latitude of the ending location
     * @param {Number} opts.endLng Longitude of the ending location
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CostEstimateResponse} and HTTP response
     */
    getCostWithHttpInfo(startLat, startLng, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'startLat' is set
      if (startLat === undefined || startLat === null) {
        throw new Error("Missing the required parameter 'startLat' when calling getCost");
      }

      // verify the required parameter 'startLng' is set
      if (startLng === undefined || startLng === null) {
        throw new Error("Missing the required parameter 'startLng' when calling getCost");
      }


      let pathParams = {
      };
      let queryParams = {
        'ride_type': opts['rideType'],
        'start_lat': startLat,
        'start_lng': startLng,
        'end_lat': opts['endLat'],
        'end_lng': opts['endLng']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Client Authentication', 'User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CostEstimateResponse;

      return this.apiClient.callApi(
        '/cost', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Cost estimates
     * Estimate the cost of taking a Lyft between two points. 
     * @param {Number} startLat Latitude of the starting location
     * @param {Number} startLng Longitude of the starting location
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.rideType ID of a ride type
     * @param {Number} opts.endLat Latitude of the ending location
     * @param {Number} opts.endLng Longitude of the ending location
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CostEstimateResponse}
     */
    getCost(startLat, startLng, opts) {
      return this.getCostWithHttpInfo(startLat, startLng, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Available drivers nearby
     * The drivers endpoint returns a list of nearby drivers&#39; lat and lng at a given location. 
     * @param {Number} lat Latitude of a location
     * @param {Number} lng Longitude of a location
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/NearbyDriversResponse} and HTTP response
     */
    getDriversWithHttpInfo(lat, lng) {
      let postBody = null;

      // verify the required parameter 'lat' is set
      if (lat === undefined || lat === null) {
        throw new Error("Missing the required parameter 'lat' when calling getDrivers");
      }

      // verify the required parameter 'lng' is set
      if (lng === undefined || lng === null) {
        throw new Error("Missing the required parameter 'lng' when calling getDrivers");
      }


      let pathParams = {
      };
      let queryParams = {
        'lat': lat,
        'lng': lng
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Client Authentication', 'User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = NearbyDriversResponse;

      return this.apiClient.callApi(
        '/drivers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Available drivers nearby
     * The drivers endpoint returns a list of nearby drivers&#39; lat and lng at a given location. 
     * @param {Number} lat Latitude of a location
     * @param {Number} lng Longitude of a location
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/NearbyDriversResponse}
     */
    getDrivers(lat, lng) {
      return this.getDriversWithHttpInfo(lat, lng)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Pickup ETAs
     * The ETA endpoint lets you know how quickly a Lyft driver can come get you 
     * @param {Number} lat Latitude of a location
     * @param {Number} lng Longitude of a location
     * @param {Object} opts Optional parameters
     * @param {Number} opts.destinationLat Latitude of destination location
     * @param {Number} opts.destinationLng Longitude of destination location
     * @param {module:model/String} opts.rideType ID of a ride type
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EtaEstimateResponse} and HTTP response
     */
    getETAWithHttpInfo(lat, lng, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'lat' is set
      if (lat === undefined || lat === null) {
        throw new Error("Missing the required parameter 'lat' when calling getETA");
      }

      // verify the required parameter 'lng' is set
      if (lng === undefined || lng === null) {
        throw new Error("Missing the required parameter 'lng' when calling getETA");
      }


      let pathParams = {
      };
      let queryParams = {
        'lat': lat,
        'lng': lng,
        'destination_lat': opts['destinationLat'],
        'destination_lng': opts['destinationLng'],
        'ride_type': opts['rideType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Client Authentication', 'User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EtaEstimateResponse;

      return this.apiClient.callApi(
        '/eta', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Pickup ETAs
     * The ETA endpoint lets you know how quickly a Lyft driver can come get you 
     * @param {Number} lat Latitude of a location
     * @param {Number} lng Longitude of a location
     * @param {Object} opts Optional parameters
     * @param {Number} opts.destinationLat Latitude of destination location
     * @param {Number} opts.destinationLng Longitude of destination location
     * @param {module:model/String} opts.rideType ID of a ride type
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EtaEstimateResponse}
     */
    getETA(lat, lng, opts) {
      return this.getETAWithHttpInfo(lat, lng, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Types of rides
     * The ride types endpoint returns information about what kinds of Lyft rides you can request at a given location. 
     * @param {Number} lat Latitude of a location
     * @param {Number} lng Longitude of a location
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.rideType ID of a ride type
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RideTypesResponse} and HTTP response
     */
    getRideTypesWithHttpInfo(lat, lng, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'lat' is set
      if (lat === undefined || lat === null) {
        throw new Error("Missing the required parameter 'lat' when calling getRideTypes");
      }

      // verify the required parameter 'lng' is set
      if (lng === undefined || lng === null) {
        throw new Error("Missing the required parameter 'lng' when calling getRideTypes");
      }


      let pathParams = {
      };
      let queryParams = {
        'lat': lat,
        'lng': lng,
        'ride_type': opts['rideType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Client Authentication', 'User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RideTypesResponse;

      return this.apiClient.callApi(
        '/ridetypes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Types of rides
     * The ride types endpoint returns information about what kinds of Lyft rides you can request at a given location. 
     * @param {Number} lat Latitude of a location
     * @param {Number} lng Longitude of a location
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.rideType ID of a ride type
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RideTypesResponse}
     */
    getRideTypes(lat, lng, opts) {
      return this.getRideTypesWithHttpInfo(lat, lng, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
