/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiError from '../model/ApiError';
import CancellationCostError from '../model/CancellationCostError';
import CancellationRequest from '../model/CancellationRequest';
import Location from '../model/Location';
import Profile from '../model/Profile';
import RatingRequest from '../model/RatingRequest';
import Ride from '../model/Ride';
import RideDetail from '../model/RideDetail';
import RideReceipt from '../model/RideReceipt';
import RideRequest from '../model/RideRequest';
import RideRequestError from '../model/RideRequestError';
import RidesResponse from '../model/RidesResponse';

/**
* User service.
* @module api/UserApi
* @version 1.0.0
*/
export default class UserApi {

    /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Cancel a ongoing requested ride
     * Cancel a ongoing ride which was requested earlier by providing the ride id. 
     * @param {String} id The ID of the ride
     * @param {Object} opts Optional parameters
     * @param {module:model/CancellationRequest} opts.request 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    cancelRideWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['request'];

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling cancelRide");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/rides/{id}/cancel', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Cancel a ongoing requested ride
     * Cancel a ongoing ride which was requested earlier by providing the ride id. 
     * @param {String} id The ID of the ride
     * @param {Object} opts Optional parameters
     * @param {module:model/CancellationRequest} opts.request 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    cancelRide(id, opts) {
      return this.cancelRideWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * The user&#39;s general info
     * The v1 of this endpoint returns the user&#39;s ID, v2 will return more general info about the user. We require authentication for this endpoint, so we extract the user ID from the access token. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Profile} and HTTP response
     */
    getProfileWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Profile;

      return this.apiClient.callApi(
        '/profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * The user&#39;s general info
     * The v1 of this endpoint returns the user&#39;s ID, v2 will return more general info about the user. We require authentication for this endpoint, so we extract the user ID from the access token. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Profile}
     */
    getProfile() {
      return this.getProfileWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get the ride detail of a given ride ID
     * Get the status of a ride along with information about the driver, vehicle and price of a given ride ID 
     * @param {String} id The ID of the ride
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RideDetail} and HTTP response
     */
    getRideWithHttpInfo(id) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getRide");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RideDetail;

      return this.apiClient.callApi(
        '/rides/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get the ride detail of a given ride ID
     * Get the status of a ride along with information about the driver, vehicle and price of a given ride ID 
     * @param {String} id The ID of the ride
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RideDetail}
     */
    getRide(id) {
      return this.getRideWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get the receipt of the rides.
     * Get the receipt information of a processed ride by providing the ride id. Receipts will only be available to view once the payment has been processed. In the case of canceled ride, cancellation penalty is included if applicable. 
     * @param {String} id The ID of the ride
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RideReceipt} and HTTP response
     */
    getRideReceiptWithHttpInfo(id) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getRideReceipt");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RideReceipt;

      return this.apiClient.callApi(
        '/rides/{id}/receipt', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get the receipt of the rides.
     * Get the receipt information of a processed ride by providing the ride id. Receipts will only be available to view once the payment has been processed. In the case of canceled ride, cancellation penalty is included if applicable. 
     * @param {String} id The ID of the ride
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RideReceipt}
     */
    getRideReceipt(id) {
      return this.getRideReceiptWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List rides
     * Get a list of past &amp; current rides for this passenger. 
     * @param {Date} startTime Restrict to rides starting after this point in time. The earliest supported date is 2015-01-01T00:00:00+00:00 
     * @param {Object} opts Optional parameters
     * @param {Date} opts.endTime Restrict to rides starting before this point in time. The earliest supported date is 2015-01-01T00:00:00+00:00 
     * @param {Number} opts.limit The maximum number of rides to return. The default limit is 10 if not specified. The maximum allowed value is 50, an integer greater that 50 will return at most 50 results.  (default to 10)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RidesResponse} and HTTP response
     */
    getRidesWithHttpInfo(startTime, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'startTime' is set
      if (startTime === undefined || startTime === null) {
        throw new Error("Missing the required parameter 'startTime' when calling getRides");
      }


      let pathParams = {
      };
      let queryParams = {
        'start_time': startTime,
        'end_time': opts['endTime'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RidesResponse;

      return this.apiClient.callApi(
        '/rides', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * List rides
     * Get a list of past &amp; current rides for this passenger. 
     * @param {Date} startTime Restrict to rides starting after this point in time. The earliest supported date is 2015-01-01T00:00:00+00:00 
     * @param {Object} opts Optional parameters
     * @param {Date} opts.endTime Restrict to rides starting before this point in time. The earliest supported date is 2015-01-01T00:00:00+00:00 
     * @param {Number} opts.limit The maximum number of rides to return. The default limit is 10 if not specified. The maximum allowed value is 50, an integer greater that 50 will return at most 50 results.  (default to 10)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RidesResponse}
     */
    getRides(startTime, opts) {
      return this.getRidesWithHttpInfo(startTime, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Request a Lyft
     * Request a Lyft come pick you up at the given location. 
     * @param {module:model/Ride} request Ride request information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RideRequest} and HTTP response
     */
    newRideWithHttpInfo(request) {
      let postBody = request;

      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling newRide");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RideRequest;

      return this.apiClient.callApi(
        '/rides', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Request a Lyft
     * Request a Lyft come pick you up at the given location. 
     * @param {module:model/Ride} request Ride request information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RideRequest}
     */
    newRide(request) {
      return this.newRideWithHttpInfo(request)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update the destination of the ride
     * Add or update the ride&#39;s destination. Note that the ride must still be active (not droppedOff or canceled), and that destinations on Lyft Line rides can not be changed. 
     * @param {String} id The ID of the ride
     * @param {module:model/Location} request The coordinates and optional address of the destination
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Location} and HTTP response
     */
    setRideDestinationWithHttpInfo(id, request) {
      let postBody = request;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling setRideDestination");
      }

      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling setRideDestination");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Location;

      return this.apiClient.callApi(
        '/rides/{id}/destination', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update the destination of the ride
     * Add or update the ride&#39;s destination. Note that the ride must still be active (not droppedOff or canceled), and that destinations on Lyft Line rides can not be changed. 
     * @param {String} id The ID of the ride
     * @param {module:model/Location} request The coordinates and optional address of the destination
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Location}
     */
    setRideDestination(id, request) {
      return this.setRideDestinationWithHttpInfo(id, request)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Add the passenger&#39;s rating, feedback, and tip
     * Add the passenger&#39;s 1 to 5 star rating of the ride, optional written feedback, and optional tip amount in minor units and currency. The ride must already be dropped off, and ratings must be given within 24 hours of drop off. For purposes of display, 5 is considered the default rating. When this endpoint is successfully called, payment processing will begin. 
     * @param {String} id The ID of the ride
     * @param {module:model/RatingRequest} request The rating and optional feedback
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    setRideRatingWithHttpInfo(id, request) {
      let postBody = request;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling setRideRating");
      }

      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling setRideRating");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['User Authentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/rides/{id}/rating', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Add the passenger&#39;s rating, feedback, and tip
     * Add the passenger&#39;s 1 to 5 star rating of the ride, optional written feedback, and optional tip amount in minor units and currency. The ride must already be dropped off, and ratings must be given within 24 hours of drop off. For purposes of display, 5 is considered the default rating. When this endpoint is successfully called, payment processing will begin. 
     * @param {String} id The ID of the ride
     * @param {module:model/RatingRequest} request The rating and optional feedback
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    setRideRating(id, request) {
      return this.setRideRatingWithHttpInfo(id, request)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
