/**
 * Lyft API
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lyft);
  }
}(this, function(expect, lyft) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lyft.CostEstimate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CostEstimate', function() {
    it('should create an instance of CostEstimate', function() {
      // uncomment below and update the code to test CostEstimate
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be.a(lyft.CostEstimate);
    });

    it('should have the property rideType (base name: "ride_type")', function() {
      // uncomment below and update the code to test the property rideType
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "display_name")', function() {
      // uncomment below and update the code to test the property displayName
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCostCentsMin (base name: "estimated_cost_cents_min")', function() {
      // uncomment below and update the code to test the property estimatedCostCentsMin
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCostCentsMax (base name: "estimated_cost_cents_max")', function() {
      // uncomment below and update the code to test the property estimatedCostCentsMax
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property estimatedDistanceMiles (base name: "estimated_distance_miles")', function() {
      // uncomment below and update the code to test the property estimatedDistanceMiles
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property estimatedDurationSeconds (base name: "estimated_duration_seconds")', function() {
      // uncomment below and update the code to test the property estimatedDurationSeconds
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property isValidEstimate (base name: "is_valid_estimate")', function() {
      // uncomment below and update the code to test the property isValidEstimate
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property primetimePercentage (base name: "primetime_percentage")', function() {
      // uncomment below and update the code to test the property primetimePercentage
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property primetimeConfirmationToken (base name: "primetime_confirmation_token")', function() {
      // uncomment below and update the code to test the property primetimeConfirmationToken
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

    it('should have the property costToken (base name: "cost_token")', function() {
      // uncomment below and update the code to test the property costToken
      //var instane = new lyft.CostEstimate();
      //expect(instance).to.be();
    });

  });

}));
